name: 'Hello World'
description: 'Greet someone'
inputs: 
  who-to-greet:  # id of input
    description: 'Who to greet'
    # settings as required AND providing a default -- redundant? (this was in the docs)
    required: true
    default: 'World' 
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  greeting:
    description: "A fine greeting"
    value: ${{ steps.greeting-generator.outputs.greeting }}
runs:
  using: "composite"
  steps:
    - id: greeting-generator
      # note that INPUT_WHO... comes from this step's env
      run: echo "greeting=$INPUT_WHO_TO_GREET" >> $GITHUB_OUTPUT
      shell: bash
      env: 
      # inputs comes from calling workflow
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
    - id: random-number-generator
      # $RANDOM is a bash variable
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    # Add action's path to the runner system path so it can locate the goodbye.sh script during execution
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
    - id: run-goodbye-js
      run: node ${{ github.action_path }}/goodbye.js
      shell: bash
